apiVersion: v1
kind: Secret
metadata:
  name: gruvit-secrets
  namespace: gruvit
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded values
  JWT_SECRET: Z3J1dml0LXN1cGVyLXNlY3JldC1qd3Qta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24tMjAyNA==
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: eW91ci1tb25nby1wYXNzd29yZA==
  JAMENDO_API_KEY: YmU2Y2I1M2Y=
  JAMENDO_CLIENT_SECRET: OTRiODU4NmI4MDUzZWUzZTJiYjFmZjM2MDZlMGU3ZDU=
  GRAFANA_PASSWORD: eW91ci1ncmFmYW5hLXBhc3N3b3Jk
